sonar.projectKey=Elysium-Labs-EU_eos-plugins
sonar.organization=elysium-labs-eu

sonar.sources=eos-sink-loki,eos-sink-otlp,eos-sink-sse,eos-sink-logbench
sonar.exclusions=**/*_test.go

sonar.tests=eos-sink-loki,eos-sink-otlp,eos-sink-sse,eos-sink-logbench
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=eos-sink-loki/coverage.out,eos-sink-otlp/coverage.out,eos-sink-sse/coverage.out,eos-sink-logbench/coverage.out
